---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: py_api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://cg5labs.github.io/helm-charts/'
    targetRevision: 0.0.1
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: replicaCount
          value: "1"
    chart: py_api
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cleanroom 
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
